### ISSUE TITLE
CI: Failures in "Create test port"

### ISSUE THREAD

**Issue by osfrickler** [osism/testbed#1544]
Some jobs are currently failing with:

```
TASK [Create test port] ********************************************************
Thursday 16 March 2023  10:06:01 +0000 (0:00:01.588)       0:00:27.253 ******** 
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": {"data": null, "details": "Request Failed: internal server error while processing your request.", "response": "{\"NeutronError\": {\"type\": \"HTTPInternalServerError\", \"message\": \"Request Failed: internal server error while processing your request.\", \"detail\": \"\"}}"}, "msg": "HttpException: 500: Server Error for url: https://api.testbed.osism.xyz:9696/v2.0/ports, Request Failed: internal server error while processing your request."}
```

No success in recreating locally so far. We likely need to include more logs in the CI output.

**Comment by berendt** [comment]
Does somehow not always occur.

**Comment by osfrickler** [comment]
Most failures seem to happen on yoga, where neutron is getting into some broken state after the initial startup. After some minutes it crashes and restarts, afterwards things seem to be working fine. Sample traceback:

```
2023-03-22 21:09:08.697 7 CRITICAL neutron [req-013b3983-fb0d-41fb-99f0-8fce595385cf - - - - -] Unhandled error: neutron_lib.callbacks.exceptions.CallbackFailure: Callback neutron.plugins.ml2.drivers.ovn.mech_driver.mech_driver.OVNMechanismDriver.pre_fork_initialize-373429 failed with "Commands [PgAddCommand(name=neutron_pg_drop, may_exist=True, columns={'acls': []}), PgAclAddCommand(entity=neutron_pg_drop, direction=from-lport, priority=1001, match=inport == @neutron_pg_drop && ip, action=drop, log=False, may_exist=True, severity=[], name=[], meter=None, external_ids={}), PgAclAddCommand(entity=neutron_pg_drop, direction=to-lport, priority=1001, match=outport == @neutron_pg_drop && ip, action=drop, log=False, may_exist=True, severity=[], name=[], meter=None, external_ids={})] exceeded timeout 180 seconds, cause: Result queue is empty"
2023-03-22 21:09:08.697 7 ERROR neutron Traceback (most recent call last):
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/bin/neutron-server", line 8, in <module>
2023-03-22 21:09:08.697 7 ERROR neutron     sys.exit(main())
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron/cmd/eventlet/server/__init__.py", line 20, in main
2023-03-22 21:09:08.697 7 ERROR neutron     server.boot_server(wsgi_eventlet.eventlet_wsgi_server)
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron/server/__init__.py", line 67, in boot_server
2023-03-22 21:09:08.697 7 ERROR neutron     return server_func()
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron/server/wsgi_eventlet.py", line 24, in eventlet_wsgi_server
2023-03-22 21:09:08.697 7 ERROR neutron     neutron_api = service.serve_wsgi(service.NeutronApiService)
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron/service.py", line 94, in serve_wsgi
2023-03-22 21:09:08.697 7 ERROR neutron     registry.publish(resources.PROCESS, events.BEFORE_SPAWN, service)
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron_lib/callbacks/registry.py", line 54, in publish
2023-03-22 21:09:08.697 7 ERROR neutron     _get_callback_manager().publish(resource, event, trigger, payload=payload)
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron_lib/db/utils.py", line 110, in _wrapped
2023-03-22 21:09:08.697 7 ERROR neutron     raise db_exc.RetryRequest(e)
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-03-22 21:09:08.697 7 ERROR neutron     self.force_reraise()
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-03-22 21:09:08.697 7 ERROR neutron     raise self.value
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron_lib/db/utils.py", line 105, in _wrapped
2023-03-22 21:09:08.697 7 ERROR neutron     return function(*args, **kwargs)
2023-03-22 21:09:08.697 7 ERROR neutron   File "/var/lib/kolla/venv/lib/python3.8/site-packages/neutron_lib/callbacks/manager.py", line 157, in publish
2023-03-22 21:09:08.697 7 ERROR neutron     raise exceptions.CallbackFailure(errors=errors)
2023-03-22 21:09:08.697 7 ERROR neutron neutron_lib.callbacks.exceptions.CallbackFailure: Callback neutron.plugins.ml2.drivers.ovn.mech_driver.mech_driver.OVNMechanismDriver.pre_fork_initialize-373429 failed with "Commands [PgAddCommand(name=neutron_pg_drop, may_exist=True, columns={'acls': []}), PgAclAddCommand(entity=neutron_pg_drop, direction=from-lport, priority=1001, match=inport == @neutron_pg_drop && ip, action=drop, log=False, may_exist=True, severity=[], name=[], meter=None, external_ids={}), PgAclAddCommand(entity=neutron_pg_drop, direction=to-lport, priority=1001, match=outport == @neutron_pg_drop && ip, action=drop, log=False, may_exist=True, severity=[], name=[], meter=None, external_ids={})] exceeded timeout 180 seconds, cause: Result queue is empty"
2023-03-22 21:09:08.697 7 ERROR neutron 
2023-03-22 21:09:08.762 923 INFO oslo_service.service [-] Parent process has died unexpectedly, exiting
2023-03-22 21:09:08.762 924 INFO oslo_service.service [-] Parent process has died unexpectedly, exiting
2023-03-22 21:09:08.763 924 INFO neutron.wsgi [-] (924) wsgi exited, is_accepting=True
2023-03-22 21:09:08.763 923 INFO neutron.wsgi [-] (923) wsgi exited, is_accepting=True
```

**Comment by osfrickler** [comment]
So far I have only seen this issue on Yoga. Seems there is a possible fix for this in a newer version of Neutron, will see whether https://github.com/osism/release/pull/834 will help.

**Comment by osfrickler** [comment]
Haven't seen the issue again since newer Neutron is being deployed.
