### ISSUE TITLE
Review of Refstack tests with OpenStack Ussuri

### ISSUE THREAD

**Issue by berendt** [osism/testbed#455]
After changing the default to OpenStack Ussuri some Refstack tests fail.

```
[ 6958.570886] cloud-init[1196]: ==============================
[ 6958.572054] cloud-init[1196]: Failed 3 tests - output below:
[ 6958.573581] cloud-init[1196]: ==============================
[ 6958.574760] cloud-init[1196]: tempest.api.network.test_ports.PortsTestJSON.test_create_update_delete_port[id-c72c1c0c-2193-4aca-aaa4-b1442640f51c,smoke]
[ 6958.576641] cloud-init[1196]: --------------------------------------------------------------------------------------------------------------------------
[ 6958.578634] cloud-init[1196]: Captured traceback:
[ 6958.579772] cloud-init[1196]: ~~~~~~~~~~~~~~~~~~~
[ 6958.580852] cloud-init[1196]:     Traceback (most recent call last):
[ 6958.582065] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/api/network/test_ports.py", line 74, in test_create_update_delete_port
[ 6958.584021] cloud-init[1196]:     body = self.ports_client.create_port(network_id=self.network['id'])
[ 6958.585492] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/services/network/ports_client.py", line 28, in create_port
[ 6958.587328] cloud-init[1196]:     return self.create_resource(uri, post_data)
[ 6958.588614] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/services/network/base.py", line 61, in create_resource
[ 6958.590386] cloud-init[1196]:     resp, body = self.post(req_uri, req_post_data)
[ 6958.591705] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/common/rest_client.py", line 279, in post
[ 6958.593410] cloud-init[1196]:     return self.request('POST', url, extra_headers, headers, body, chunked)
[ 6958.594966] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/common/rest_client.py", line 670, in request
[ 6958.596645] cloud-init[1196]:     self._error_checker(resp, resp_body)
[ 6958.597856] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/common/rest_client.py", line 847, in _error_checker
[ 6958.599891] cloud-init[1196]:     message=message)
[ 6958.600998] cloud-init[1196]:     tempest.lib.exceptions.ServerFault: Got server fault
[ 6958.602350] cloud-init[1196]: Details: Request Failed: internal server error while processing your request.
[ 6958.604060] cloud-init[1196]: Captured pythonlogging:
[ 6958.605170] cloud-init[1196]: ~~~~~~~~~~~~~~~~~~~~~~~
[ 6958.606357] cloud-init[1196]:     2020-10-02 05:00:52,883 32446 INFO     [tempest.lib.common.rest_client] Request (PortsTestJSON:test_create_update_delete_port): 500 POST http://api.osism.test:9696/v2.0/ports 11.169s
[ 6958.608711] cloud-init[1196]: tempest.api.object_storage.test_account_quotas.AccountQuotasTest.test_upload_valid_object[id-a22ef352-a342-4587-8f47-3bbdb5b039c4,smoke]
[ 6958.610715] cloud-init[1196]: ----------------------------------------------------------------------------------------------------------------------------------------
[ 6958.612766] cloud-init[1196]: Captured traceback:
[ 6958.613875] cloud-init[1196]: ~~~~~~~~~~~~~~~~~~~
[ 6958.614988] cloud-init[1196]:     Traceback (most recent call last):
[ 6958.616220] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/api/object_storage/test_account_quotas.py", line 57, in setUp
[ 6958.617969] cloud-init[1196]:     "POST", url="", headers=headers, body="")
[ 6958.619242] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/common/rest_client.py", line 670, in request
[ 6958.621028] cloud-init[1196]:     self._error_checker(resp, resp_body)
[ 6958.622308] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/common/rest_client.py", line 771, in _error_checker
[ 6958.624039] cloud-init[1196]:     raise exceptions.Forbidden(resp_body, resp=resp)
[ 6958.625608] cloud-init[1196]:     tempest.lib.exceptions.Forbidden: Forbidden
[ 6958.626894] cloud-init[1196]: Details: b'AccessDenied'
[ 6958.628038] cloud-init[1196]: Captured pythonlogging:
[ 6958.629182] cloud-init[1196]: ~~~~~~~~~~~~~~~~~~~~~~~
[ 6958.630318] cloud-init[1196]:     2020-10-02 05:04:45,982 32446 INFO     [tempest.lib.common.rest_client] Request (AccountQuotasTest:setUp): 403 POST http://api.osism.test:8080/swift/v1/AUTH_e1214f0c1f4d49f1a51b5760a0c7f607 0.078s
[ 6958.632816] cloud-init[1196]: tempest.api.object_storage.test_account_quotas_negative.AccountQuotasNegativeTest.test_user_modify_quota[id-d1dc5076-555e-4e6d-9697-28f1fe976324,negative]
[ 6958.634934] cloud-init[1196]: ----------------------------------------------------------------------------------------------------------------------------------------------------------
[ 6958.637030] cloud-init[1196]: Captured traceback:
[ 6958.638138] cloud-init[1196]: ~~~~~~~~~~~~~~~~~~~
[ 6958.639250] cloud-init[1196]:     Traceback (most recent call last):
[ 6958.640475] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/api/object_storage/test_account_quotas_negative.py", line 56, in setUp
[ 6958.642314] cloud-init[1196]:     "POST", url="", headers=headers, body="")
[ 6958.643634] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/common/rest_client.py", line 670, in request
[ 6958.645411] cloud-init[1196]:     self._error_checker(resp, resp_body)
[ 6958.646686] cloud-init[1196]:       File "/opt/refstack/client/.tempest/tempest/lib/common/rest_client.py", line 771, in _error_checker
[ 6958.648412] cloud-init[1196]:     raise exceptions.Forbidden(resp_body, resp=resp)
[ 6958.649971] cloud-init[1196]:     tempest.lib.exceptions.Forbidden: Forbidden
[ 6958.651278] cloud-init[1196]: Details: b'AccessDenied'
[ 6958.652426] cloud-init[1196]: Captured pythonlogging:
[ 6958.653553] cloud-init[1196]: ~~~~~~~~~~~~~~~~~~~~~~~
[ 6958.654664] cloud-init[1196]:     2020-10-02 05:04:49,126 32446 INFO     [tempest.lib.common.rest_client] Request (AccountQuotasNegativeTest:setUp): 403 POST http://api.osism.test:8080/swift/v1/AUTH_e1214f0c1f4d49f1a51b5760a0c7f607 0.062s
```

**Comment by berendt** [comment]
```
[ 8137.647555] cloud-init[1220]: ======
[ 8137.647680] cloud-init[1220]: Totals
[ 8137.647835] cloud-init[1220]: ======
[ 8137.647940] cloud-init[1220]: Ran: 288 tests in 1563.0282 sec.
[ 8137.648220] cloud-init[1220]:  - Passed: 277
[ 8137.648499] cloud-init[1220]:  - Skipped: 11
[ 8137.648597] cloud-init[1220]:  - Expected Fail: 0
[ 8137.648715] cloud-init[1220]:  - Unexpected Success: 0
[ 8137.648974] cloud-init[1220]:  - Failed: 0
[ 8137.649116] cloud-init[1220]: Sum of execute time for each test: 1079.6739 sec.
```
